# Introduction

## Basic Information

`r Spp` (*`r spp.sci`*, or `black cod') are distributed in the Northeastern Pacific Ocean from the southern tip of Baja California northward to the North-Central Bering Sea and in the Northwestern Pacific Ocean from Kamchatka southward to the northeastern coast of Japan [@hart_pacific_1973; @eschmeyer_field_1983]. Despite their vast range, U.S. West Coast `r spp` are modeled as a single population. Thus, this assessment does not explicitly account for movement between offshore sea mounts [@shaw_movement_1997; @morita_sex_2012, @hanselman_move_2015], regions to the north of the U.S. West Coast, or to the Western Pacific [@fujioka_description_1988; @heifetz_movement_1991; @hanselman_move_2015]. To the modelers' knowledge there is no information from the Pacific Coast of Mexico.

While previous analyses suggest the existence of several stocks of `r spp` in the Eastern Pacific Ocean that are largely delineated by management boundaries [@schirripa_status_2007] and earlier assessments. More recent genetic analyses found that `r spp` in the Northeastern Pacific Ocean are a single panmictic population [@jasonowicz_love_2017]. Additional support for a panmictic population stems from tag recoveries that show `r spp` move between the regions currently used for management [@hanselman_move_2015, @sogard_patterns_2017]. Analyses of length-at-age data has found spatial variation in von Bertalanffy growth parameters across the Northeastern Pacific Ocean [@mcdevitt_status_1987; @echave_interdecadal_2012; @head_maturity_2014, @gertseva_spatial_2017, @kapur_oceanographic_2020]. While geographic break points at approximately 36\textdegree~N, between Point Conception and Monterey, California at the start of the Southern California Bight, and 50\textdegree~N, where the North Pacific Current bifurcates, suggest zones of growth variation, generally with increasing maximum body size and decreasing growth rates with increasing latitude, they do not indicate regions with separate populations.

Smaller `r spp` are generally found in shallower waters but the demographics appears to be fully mixed (adult and juvenile) near the shelf-slope break (i.e., 100--300 m). Beyond the shelf--slope break, the adult population is dominated by older individuals [@methot_assessment_1994] and younger fish become increasingly rare. Fish in the deepest areas sampled tend to be the oldest individuals, but not the largest individuals, suggesting that age rather than size dictates depth distribution. However, the interaction between environmental conditions and seasonal movements that produce an increase in age with depth are largely unknown. The population is distributed beyond the greatest depth sampled by any of the surveys and beyond the deepest commercial fishing areas. Research in these deeper habitats occupied by `r spp` is potentially difficult because they extend across the boundary of the exclusive economic zone and sea mounts and ridges around the Pacific. There are relatively fewer `r spp` in the Puget Sound and the Strait of Georgia than in coastal U.S. waters. Therefore, connectivity among these areas and the open coast is likely of less importance to this assessment than movement along the coast.

## Life History

@tolimieri_oceanographic_2018 provide a thorough review of the literature on spawning and early life history of `r spp` in the `r coast`. Briefly, `r spp` off the `r coast` exhibit a protracted spawning period from December through March, with peak in February [@guzman_reproductive_2017]. This winter-time spawning may result in reduced availability to the commercial fishery during the winter months. Spawning occurs along the continental shelf--slope break in waters deeper than 300 m. Eggs ($\sim$ 2.1 mm in diameter) are buoyant and rise in the water column before hatching and sinking to deeper waters. Pelagic juveniles are present in off-shore surface waters and settle to the benthos as age-0 recruits during the late summer to fall, with most newly settled fish at depths of less than 250 m. 

`r Spp` reach full size and maturity in their first decade of life, reaching nearly asymptotic size and beginning to mature after 5--7 years. Female `r spp` generally reach larger sizes than males. However, the sex ratio tends to be skewed toward males at the oldest ages implying a lower natural mortality rate for males relative to females. The oldest `r spp` on record was captured in 2006 off Washington and aged (with observation error) at 102 years. This female was only 68 cm long, nowhere near the longest individual (117 cm).

Adult `r spp` are fast swimming and capable of feeding on a diverse array of prey species including fishes, cephalopods, and crustaceans [@low_sablefish_1976]. The cohabitation of adult and juvenile `r spp` may result in some cannibalism, and large changes in predator biomass (such as the recent rebuilding of lingcod, \emph{Ophiodon elongatus}) could have a feedback on juvenile survival and, therefore, stock productivity.

Range-wide investigations of `r spp` growth suggest that growth varies across the Northeastern Pacific, with a generally increasing cline in length-at-age data with latitude [@mcdevitt_status_1987; @echave_interdecadal_2012; @gertseva_spatial_2017, @kapur_oceanographic_2020]. Break points in growth have been identified at around 50\textdegree~N (approximately the northern end of Vancouver Island, Canada), where north of this breakpoint female asymptotic-length estimates were consistently over 70 cm and south of this breakpoint female asymptotic-length estimates were below 66 cm [@Kapur:2021:SSA]. A second break point was identified by @kapur_oceanographic_2020 at 36\textdegree~N (approximately Monterey, California), where asymptotic size for females and males to the south were 60.43 cm and 55.00 cm, respectively. Note that this information was not included in the 2019 benchmark assessment nor this update, as the data to construct a spatially-structured model and account for movement between areas north and south of 36\textdegree~N are not available. Instead, coastwide, sex-specific growth parameters were estimated for females and males, as it was done in 2019 benchmark assessment.

## Ecosystem Considerations

A detailed summary of \gls{ses} analyses, the Climate Vulnerability Assessment, and environmental drivers of sablefish recruitment is available in the 2019 Benchmark Assessment report [@haltuch_status_2019b].

### Oceanographic drivers of recruitment

TO DO: Add any new text for Nick 

## Historical and Current Fishery Information

Historical `r spp` landings, beginning in 1890, have been reconstructed by the states (Washington, Oregon, and California) using a variety of sources. Generally, historical `r spp` landings were more reliable than those for many other groundfish species because of their consistent species-level identification. While `r spp` landings were recorded back to the beginning of the 20th century, appreciable quantities were not landed until 1916--1919, with landings remaining below 5,000 mt through the late 1960s (Table \@ref(tab:landings) and Figure \@ref(fig:data-landings)). Landings prior to 1960 were primarily harvested by hook-and-line gear. The peak around World War II was likely due to a relaxed degree of species sorting rather than a dramatic increase in fishing effort. Grey literature notes a decrease in manpower with the onset of the war, which would explain the dexcreased sorting of fish to species. Despite this decrease in manpower there were also increases in demands for domestic sources of protein [@browning_fisheries_1980].

The `r spp` fishery increased dramatically during the 1970s, first from a combination of foreign vessels [@lynde_historical_1986; @mcdevitt_status_1987], followed by an increase in the domestic fleet. Increases correspond to the introduction of a pot fishery followed by an increase in the catch coming from the trawl sector. Only minor increases were experienced in the hook-and-line sector until the mid-1980s. Large catches by foreign vessels, fishing pot gear, in 1976 resulted in the largest single-year removal of over 25,000 mt from U.S. West Coast waters. A rapid rise in domestic pot and trawl landings followed this peak removal, such that on average, nearly 14,000 mt of `r spp` were landed per year between 1976 and 1990. During the most recent decade, annual landings have remained below 10,000 mt, composed of approximately `r round(mean(model$catch[model$catch$Fleet == 1 & model$catch$Yr > (model$endyr-10),"Obs"]))` from fixed gear and `r round(mean(model$catch[model$catch$Fleet == 2 & model$catch$Yr > (model$endyr-10),"Obs"]))` from trawl gear during the most recent decade. The decline in domestic landings through the 1980s was likely due to a combination of declining stock size, many years with below average recruitment, reduced Asian-market strength, and increasing fishery regulations.

## Summary of Management History and Performance

From the early 1900s to the early 1980s, management of the `r spp` fishery was the responsibility of the individual coastal states (California, Oregon, and Washington). Since the adoption of the Groundfish Fishery Management Plan by the \gls{pfmc} in 1982, responsibility has rested with the federal government and the \gls{pfmc}. From 1977 to the mid-1980s, U.S. commercial fishermen took advantage of their newly protected fishing grounds (i.e., the enactment of the `Fishery Conservation and Management Act', which occurred in in 1976, later to be renamed `Magnuson Stevens Fishery Conservation and Management Act') recording high catches of `r spp` to meet the demands of flourishing export (primarily Asian countries) and domestic markets.

The first coastwide regulations off the U.S. Pacific Coast for the `r spp` fishery were implemented as trip limits in October 1982, followed by a rich history of management via seasons, size-limits, trip-limits, and a complex permit system (see Appendix 10 of @haltuch_status_2019b for a comprehensive list of management actions). Beginning in 1983, additional trip limits were imposed on landings of `r spp` less than 22 in in length, considered incidental catch. In 1987, allocations between the trawl and non-trawl fleets were implemented.

Beginning in the late-1980s, the fixed-gear `r spp` fishery was managed as a `derby' fishery, characterized by successive reductions in season lengths. In 1991, the fully open season lasted seven weeks, from April 1 through May 23. In 1992, approximately 1,300 mt were landed under early season trip limits of up to 1,500 lbs per day, and the fully open season lasted from May 12 through May 26. In 1993, there was a 250 lbs per day trip limit prior to the open season which extended from May 12 through June 1, 1993. In 1994, the fully open season was shortened to May 15 through June 3, 1994. In 1995, the open season lasted ten days, August 3--13, 1995. The open season spanned only six days in 1996, from September 1--6, 1996. In 1997, ten days (August 25 to September 3) were set aside for the open season, with a mop-up period from October 1--15, 1997. In the more recent period, the Limited Entry Fixed Gear sector has been managed primarily through the use of tiered cumulative limits (allocated on the basis of historical landings) which can be landed throughout the seven-month season. The remaining open-access fishery and some limited-entry non-trawl vessels are allowed to make smaller landings that are subject to daily\slash weekly limits and two-month cumulative caps.

Additionally, `r spp` are harvested by the trawl fishery in association with a variety of other species that are distributed to domestic and foreign markets. Prior to 2011, the trawl fishery was managed primarily through the use of trip limits. These evolved from simple per-trip limits in the 1980s to cumulative periodic (monthly or bi-monthly) limits by the mid-1990s. In addition to `r spp`-specific limits, various limits were in place for the overall landings of deep-water complex species [@stewart_status_2011].

Coastwide yield targets are divided among the different gears, fishery sectors (including both limited entry and open access), as well as north and south of 36\textdegree latitude. The \gls{ofl} for `r spp` has ranged from 6,621 to 11,577 mt between 2013-2025. \Glsplural{acl} ranged from 5,451 to 10,824 mt over the same period. Landings have been estimated to be below the \glsplural{acl} in all years.

## Foreign Fisheries

Similarly to the U.S. West Coast, `r spp`, fisheries in Alaska and British Columbia waters began in the late 1800s, with generally low catches until after World War II. Foreign fisheries began exploiting `r spp` in the Northeastern Pacific Ocean during the late 1950s in the Bering Sea leading to rapidly increasing catches in the region through the 1980s. 
Historically, Alaskan landings were much larger than those off the U.S. West Coast, rising to over 20,000 mt during the early 1960s, with many years above this level until the mid-1990s. In the most recent decade, Alaskan landings, including those taken from inside waters under the management of the \gls{adfg}, have averaged just over 12,000 mt (pers. comm., B. Williams; see and @hanselman_chapter_2018 for a full account of `r spp` fisheries in Alaska).

The `r spp` fishery in British Columbian waters has a similar history to those in U.S. waters. The fishery primarily uses pots, with a lesser amount landed using long lines and trawls. Landings ranged up to just over 7,000 mt during the mid-1970s, followed by a variable but generally declining trend through the present (@kronlund_management_2011; pers. comm., B. Connors). In the most recent decade, average landings have been just over 2,100 mt, with the 2014 landings representing the lowest since the the mid-1960s (pers. comm., B. Connors).
