# Data

<!--
Data comprise the foundational components of stock assessment models.
The decision to include or exclude particular data sources in an assessment model depends on many factors.
These factors often include, but are not limited to,
the way in which data were collected (e.g., measurement method and consistency);
the spatial and temporal coverage of the data;
the quantity of data available per desired sampling unit;
the representativeness of the data to inform the modeled processes of importance;
timing of when the data were provided;
limitations imposed by the Terms of Reference; and
the presence of an avenue for the inclusion of the data in the assessment model.
Attributes associated with a data source can change through time,
as can the applicability of the data source when different modeling approaches are explored (e.g., stock structure or time-varying processes).
Therefore, the specific data sources included or excluded from this assessment should not necessarily constrain the selection of data sources applicable to future stock assessments for `r spp`.
Even if a data source is not directly used in the stock assessment they can provide valuable insights into biology, fishery behavior, or localized dynamics.

Data from a wide range of programs were available for possible inclusion in the current assessment model.
Descriptions of each data source included in the model (Figure \@ref(fig:data-plot)) and sources that were explored but not included in the base model are provided below.
Data that were excluded from the base model were explicitly explored during the development of this stock assessment or have not changed since their past exploration in a previous `r spp` stock assessment.
In some cases, the inclusion of excluded data sources were explored through sensitivity analyses (see Section \@ref(assessment-model)).
-->

Only data sources (Figure \@ref(fig:data-summary)) with recently collected information were updated within this `r document_type`, which followed a more limited approach to updating data compared to a typical update assessment as agreed upon by the \gls{pfmc} on [23 April 2023](https://www.pcouncil.org/april-2023-decision-summary-document/). Therefore, only the following data sources were updated for this `r document_type`:

\begin{enumerate}
  \item The adding of recent 2021--2022 commercial landings to the model identified three issues in the landings data for the 2021 update assessment, which likely extended to previous assessments as well. First, select landings from \gls{pacfin} were omitted. These landings have been added to this `r document_type` (see section \@ref(commercial-landings) for additional information). Second, landings from 1977--1982 in the catch reporting area that includes both U.S. and Canadian waters are now assigned 50--50\% to the respective countries rather than 100\% to the U.S.A. Finally, previous assessments failed to include bycatch of `r spp` from the Pacific Hake (*Merluccius productus*) At-Sea Fishery in the base model. Annual bycatch of `r spp` is typically low but can experience sharp increases following years with large recruitment events (e.g., 304 mt in 2022).
  \item The discard mean weights and length compositions from discarded fish observed by \gls{wcgop} were updated and the new values for 2020 and 2021 were added to the model. Discard rates from 2020 to 2021 were added to the model. 
  \item The relative index of abundance, length-composition, and conditional-age-at-length data from the \gls{s-wcgbt} were updated and extended through 2022.
  \item The environmental index data to inform estimation of recruitment were updated and extended through 2022.
\end{enumerate}

All other data sources used in the `r spp` assessment were retained in the same form as included in the 2021 update assessment.
