## Fishery-Dependent Data

### Commercial Landings

Historical commercial landings prior to 1970, 1986, and 1980 for Washington, Oregon, and California, respectively, remained unchanged from the 2019 benchmark assessment. Landings data were pulled from \gls{pacfin} (17 July 2023) and re-evaluated for this `r document_type`.

Changes to recent landings from \gls{pacfin} include typical updates to historical data given standard updates to fish-ticket data that normally results in changes of just a few mt per year. Additional changes to the data were made because of two changes in the methods used to extract the data. First, landings from the `Oregon Coast' \gls{inpfc} area, i.e., between 42.000--46.267\textdegree N. latitude, are no longer excluded from the total landings. These 1980--2011 landings sum to approximately 4,060 mt. Second, 1977--1982 landings from the catch reporting area that includes both U.S. and Canadian waters are now assigned 50--50\% to each country rather than 100\% to the U.S. waters. More specific information for both of these changes is not reported here given confidentiality rules. Both of these changes were approved by state representatives prior to their use in this assessment.

This `r document_type` also includes data on bycatch of `r spp` by the Pacific Hake At-Sea fishery since 1990 from the \gls{afsc} \gls{norpac} database (27 July 2023). These data were not included in the landings used in the 2019 benchmark and 2021 update assessments. Across most years the bycatch of `r spp` in the Pacific Hake At-Sea fishery is relatively low, particularly compared to the landings data from other groundfish sectors contained in \gls{pacfin}.  However, there have been select years where the bycatch of `r spp` in this fishery has been higher than average, which seems to correspond to one or two year after strong `r spp` recruitment events (e.g., bycatch of 153 mt and 116 mt in 2017 and 2018, respectively). The bycatch of `r spp` in this fishery in 2022 of 304 mt was greater than any other year in the time series (1990--2022). These data were added to trawl landings during the bridging process. The full time series, i.e., back to 1978, was not available for this `r document_type`. Future assessments will want to include the full time series.

### Commercial Discard

\gls{wcgop} estimates of commercial discards and biological data from 2020 and 2021 were added to the `r document_type` model. The 2021 update assessment process experienced challenges while adding the 2019 discard data, which appeared to depart in the frequency of `r spp` being discarded and the size of discarded fish, requiring a new retention block for the trawl and fixed-gear fleets for 2019 and 2020. Including the most recent \gls{wcgop} data in this `r document_type` allowed for these data to better inform the estimation of recent discarding practices which may be changing due to large recent recruitment events.

The discard rates in the trawl fleet are similar between 2020 and 2021 but are increased compared to the 2019 rates (`r subset(information_discard_figures, fleet_number == 2 & type == "discard rate")[["label_text"]]`). The increased observed discard rate in the trawl fleet aligns with reports from the fishery of increased encounters with young, small fish in recent years. The discard rates of the fixed-gear fleet in 2020 and 2021 were similar or slightly greater than the observed 2019 rates but 2020 and 2021 had larger uncertainty (`r subset(information_discard_figures, fleet_number == 1 & type == "discard rate")[["label_text"]]`). The discard rate data were assumed to be normally distributed and fit by year in the model. Rates prior to 2020 were not updated for this `r document_type`.

The mean body weight of discarded fish by the fixed-gear fleet are similar in 2022 and 2021 to those observed in 2019 (`r subset(information_discard_figures, fleet_number == 1 & type == "body weight")[["label_text"]]`). The mean body weight of discarded fish by the trawl fleet has been declining annually since 2019 with increased variability in the body weights of discarded fish in the final year of data (`r subset(information_discard_figures, fleet_number == 2 & type == "body weight")[["label_text"]]`).

The observed length distribution of fish discarded by the fixed-gear fleet in 2020 and 2021 ranged between 40 cm and 60 cm, peaking around 50--55 cm (`r subset(information_comp_figures, partition == 1 & fleet_number == 1)[["label_text"]]`). In contrast, the lengths discarded by the trawl fleet were generally smaller (e.g., 20--55 cm; `r subset(information_comp_figures, partition == 1 & fleet_number == 2)[["label_text"]]`).
