### \acrlong{s-wcgbt}

The \gls{s-wcgbt} is based on a random-grid design; covering the coastal waters from a depth of 55--1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two `passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. There were only two vessels used in 2019 and three in 2013, with one of the three that year unable to complete its survey pass due to a government shutdown. No survey occurred in 2020 due to \gls{covid}. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders. 


#### Relative Index of Abundance

`r Spp` are observed across the full sampling depth range of the \gls{s-wcgbt} (Figure \@ref(fig:data-survey-wcgbt-proportion-by-depth)) and across all latitudes off the West Coast (Figure \@ref(fig:data-survey-wcgbt-proportion-by-latitude)). The \gls{s-wcgbt} across most years, has 400 or more positive tows for `r spp` each year (Table \@ref(tab:data-survey-n)). 

A coastwide relative index of abundance was estimate for `r spp` using the species distribution modeling platform sdmTMB [@Anderson:2022:SRP]. A delta model with a gamma error distribution was selected based on the Q-Q plots (Figure ADD QQ PLOT HERE). This was the same error distribution selected by the 2019 benchmark assessment and the 2021 assessment update.  The relative index of abundance for `r spp` decreased to the lowest levels between 2008--2010, begun to slowly increase between 2011--2019, and then sharply increase in the final two years of the time series, 2021--2022, to the highest levels observed by the \gls{s-wcgbt} (Figure \@ref(fig:data-survey-wcgbt-index)).  

#### Composition Data

Length and age samples collected annually by the \gls{s-wcgbt} were processed using 2 cm length bins between 18 to 90 cm and age bins between 0 to 50. The age data were input as conditional-age-at-length data for all years from the survey to inform the estimation of growth within the model. The length compositions were expanded to the tow level and the up the the strata level. The same stratification was selected as used in the 2019 benchmark assessment and 2021 assessment update. The stratification by area and depth is shown in Table \@ref(tab:data-strata).

The 2021 and 2022 annual length compositions for fish less than 30 cm indicate potentially multiple above average recruitments entering the population (Figure \@ref(fig:data-survey-wcgbt-lengths)). The age data in 2021 also shows above average observations of age-0 and age-1 fish with these same cohorts also being observed in 2022 (Figure \@ref(fig:data-survey-wcgbt-ages)).  The size-at-age of age-0 and age-1 fish by pass of the \gls{s-wcgbt} were examined to better understand how the sizes of young fish in 2021 and 2022 compare to other years in the time series (Figure \@ref(fig:data-survey-wcgbt-young-length-by-year)). Across all years, age-0 fish are observed more frequently during the second pass of the survey wit age-0 fish generally being less than 30 cm.  The size of age-1 fish generally range between 30-45 cm with sizes increasing across passes of the survey. The distribution of age-1 sizes observed in 2021 and 2022 is more variable compared to most other years in the time series.  Additionally, the distribution of sizes in age-1 fish varied between 2021 and 2022 with observed fish being slightly smaller by pass in 2022 compared to 2021 (Figure \@ref(fig:data-survey-wcgbt-young-length-by-year)).  The observed length distribution of fish discarded by the fixed gear fleet in 2020 and 2021 ranged between 40--60 cm, peaking around 50--55 cm (Figure \@ref(fig:data-wcgop-discard-len-fixed)). In contrast, the discarded length by the trawl fleet were generally smaller ranging between 20--55 cm (Figure \@ref(fig:data-wcgop-discard-len-trawl)).
