# Assessment Model

## Previous assessments and reviews

### History of modeling approaches

## Model structure, assumptions, and results

### Model changes from the last assessment

The following is a brief list of changes that were made to the model configuration compared to the previous assessment [@haltuch2019lingcod]. # to do fix this reference

- **Data**

  - 

- **Fleet structure**

  -

- **Biology**

  - 

- **Recruitment**

  - 

- **Selectivity and retention**

 - 

- **Software and workflow**

  - Use a newer version of Stock Synthesis, version 3.30.17.01. # to do make this number right
  - Use previously unavailable or updated versions of numerous R packages related to processing input and output files for the assessment, including _nwfscDiag_, _sa4ss_, _r4ss_, and _PacFIN.Utilities_.
  - Created a [_sablefish_](https::/github.com/pfmc-assessments/sablefish) R package in a publicly accessible GitHub repository to provide a transparent and reproducible system for processing the data, modifying the model files, and writing these reports.

### Most recent STAR panel and SSC recommendations

### Response to Groundfish Subcommittee recommendations

### Model parameters

### Base model selection

### Base model results

### Model diagnostics

#### Convergence

#### Sensitivity analyses

#### Likelihood profiles

#### Retrospective analysis

### Evaluation of uncertainty

### Reference points

### Decision table

### Unresolved problems and major uncertainties

### Research and data needs
