## Model Structure and Assumptions

### Description of New Modeling Approaches

This section is not required for an update assessment.

### Modeling Platform and Structure

The assessment was conducted using \gls{ss3} version `r ss3_version[["current"]]` developed by Dr. Richard Methot at \gls{noaa}, \gls{nwfsc} [@methot_stock_2013]. This most recent version was used because it included improvements and corrections not available in the previously used version of \gls{ss3}, i.e., version `r ss3_version[["previous"]]`.
Bridging between the previous and current base model is discussed in Section \@ref(model-changes-from-the-last-assessment). The R package [r4ss](https://github.com/r4ss/r4ss), version `r packageVersion("r4ss")`, was used to investigate and plot model fits.

### Model Changes from the Last Assessment

A brief list of changes that were made to the model configuration compared to the previous assessment [@Kapur:2021:SSA] are listed below.

- **Data**

  - The landings time series was both corrected (i.e., inclusion of Oregon Coast \gls{inpfc} area data, exclusion of Canadian landings, and inclusion of bycatch of `r spp` in the Pacific Hake At-Sea fishery since 1990) and updated from the previous assessment. See Section \@ref(data) for more details on each of these changes. None of the changes in the catch time series led to changes in the fit to the \gls{s-wcgbt} index (Figure \@ref(fig:bridging-1-compare13)). Corrections to the historical time series led to a slight increase in $R_0$ and thus also the remainder of the time series in spawning biomass (Figure \@ref(fig:bridging-1-compare1)) but not changes fraction unfished (Figure \@ref(fig:bridging-1-compare3)).
  - The \gls{s-wcgbt} relative index of abundance was updated with the most recent data using _sdmTMB_ (Figure \@ref(fig:bridging-2-compare13)). Updating the index led to changes in $R_0$ but little change in recent biomass (Figures \@ref(fig:bridging-2-compare1)--\@ref(fig:bridging-2-compare3)), and thus, the recent population status is at a lower fraction unfished than the previous base model.
  - Updating and including recent compositional information from the fishery discarded lengths, survey lengths, and survey ages led to noticeable changes in the model output but should be looked at in aggregate after the model was re-tuned with these data rather than as individual changes to the base model (Figures \@ref(fig:bridging-2-compare13)--\@ref(fig:bridging-2-compare3)).
  - The survey length-composition data were input as either sexed or unsexed fish rather than assigning a sex to unsexed fish based on the observed sex ratio, as was done in the past, which led to an increase in $R_0$ (Figures \@ref(fig:bridging-2-compare1)--\@ref(fig:bridging-2-compare3)) and the trend in abundance from the \gls{s-wcgbt} index (Figure \@ref(fig:bridging-2-compare13)).
  - The index for the environmental linkage was updated, which resulted in very little changes to the model output (Figures \@ref(fig:bridging-2-compare13)--\@ref(fig:bridging-2-compare3)).
  - Information on mean body weight of the discarded fish were updated and data from the most recent years were included (Figures \@ref(fig:bridging-3-compare13)--\@ref(fig:bridging-3-compare3)).
  - Information on discard rates from the most recent years were included and the input variance for these two most recent years in the trawl fleet was set to 0.05 (Figures \@ref(fig:bridging-3-compare13)--\@ref(fig:bridging-3-compare3)).

- **Fleet structure**

  - Essentially, no changes were made to the fleet structure used in the model. Benign remnants of the pot fleet, which was removed in 2019, were removed from the model files.

- **Biology**

  - No changes were made to the biological parameterization of the model.

- **Recruitment**

  - The bias adjustment ramp was updated to end with the last year of catches and begin to ramp down towards zero two years prior. Other parameters in the ramp were left as they were specified in the 2019 assessment. Note that the traditional method for estimating these parameters, which occurs external to the model, can often lead to the ramp starting years before composition data are available because of the inclusion of the environmental index.

- **Selectivity and retention**

  <!-- SizeSel_PRet_1_FIX(1)_BLK2repl_2019 -->
  - The ascending inflection for size-based retention within the fixed-gear fleet in the 2019 time block was fixed at the lower bound of 10 given that it was consistently estimated at this lower bound during the bridging analysis (Figures \@ref(fig:bridging-3-compare13)--\@ref(fig:bridging-3-compare3)).
  <!-- AgeSel_P_4_TWL(2)_BLK5repl_2011 -->
  - The descending width for age-based selectivity within the trawl fleet in the 2011 time block was fixed at the upper bound of 10 given that it was consistently estimated at this upper bound during the bridging analysis (Figures \@ref(fig:bridging-3-compare13)--\@ref(fig:bridging-3-compare3)).
  <!-- AgeSel_P_3_FIX(1)_BLK4repl_2011 INIT was lowered to facilitate its estimation. -->

- **Software and workflow**

  - Use a newer version of \gls{ss3}, version `r ss3_version[["current"]]`.
  - Use updated versions of numerous R packages related to processing input and output files for the assessment, including _nwfscDiag_, _sa4ss_, _r4ss_, and _PacFIN.Utilities_.
  - Created [_sablefish_](https::/github.com/pfmc-assessments/sablefish), an R package stored on GitHub, to provide a transparent and reproducible system for processing the data, modifying the model files, and writing these reports.

### Key Assumptions and Structural Choices

With the exceptions noted in Section \@ref(model-changes-from-the-last-assessment), the general model specifications were retained from the previous assessment to conform to the \gls{tor} for an `r document_type`. The model is sex-specific, including the estimation of separate growth curves and natural mortality parameters for males and females. The sex ratio at birth is assumed to be `r sex_ratio_text`. Female spawning biomass is used in calculating stock status. The model starts at equilibrium, assuming an unfished initial age structure in `r startyr - 1`. The internal population dynamics include ages `r paste(sep = "--", c(age_bins[1]), model[["accuage"]])`, where age `r model[["accuage"]]` is the beginning of the plus group. The data use a plus-group age of `r max(age_bins)` because there is little growth occurring at the model plus-group age and very few observations.

### Priors
 
The prior distributions for natural mortality ($M$) by sex remain the same as what was assumed in the 2019 benchmark assessment and were based on the @hamel_method_2015 and @hamel_development_2022 meta-analytic approach with an assumed maximum age of 102 years for females and 98 for males. The priors assumed a log normal distribution with a median of
`r model[["parameters"]] |> dplyr::filter(grepl("NatM", Label)) |> dplyr::pull(Prior) |> exp() |> sprintf(fmt = "%.3f") |> paste(collapse = " and ")`
yr$^{-1}$ and a standard error of
`r model[["parameters"]] |> dplyr::filter(grepl("NatM", Label)) |> dplyr::pull(Pr_SD) |> sprintf(fmt = "%.3f") |> paste(collapse = " and ")`
for females and males, respectively.

### Data Weighting

Length data from the \gls{s-wcgbt} and fishery discards, conditional age-at-length compositions from the \gls{s-wcgbt}, and marginal age compositions from the fishery fleets and other surveys were fit and appropriately weighted using an iterative approach. The Francis method (Table \@ref(tab:composition-weight)), which is based on equation TA1.8 in Francis [-@francis_data_2011], was used with three iterations to tune the length and age data simultaneously. For conditional-age-at-length data, it was assumed that each age was a random sample within the length bin, and thus, the model started with a sample size equal to the number of fish in that length bin. A sensitivity is included to examine differences in parameter estimates when data weighting of the age and length data used the McAllister--Ianelli [@mcallister_bayesian_1997] method, which is based on the harmonic mean.

Additional variance was estimated and added to the input variance for the following three relative indices of abundance: \gls{s-tri} both early and late, \gls{s-nslope}, and \gls{s-aslope}, as well as the environmental index. Estimating additional variance for the \gls{s-wcgbt} was explored in a sensitivity and determined to be different than zero but was not included in the base model because it previously had not been included.

Added variances for discard rates and mean body weights were set using values calculated iteratively using the \gls{rmse} of differences between input and estimated values derived from \gls{ss3}. These variances were parameterized in terms of standard deviation and coefficient of variation, respectively.

### Model Parameters

There were `r model[["parameters"]] |> dplyr::filter(Phase > 0) |> NROW()` estimated parameters in the base model. These included one parameter for $R_0$; 10 parameters for growth; 2 parameters for sex-specific natural mortality; 4 parameters for extra variability for the survey indices; 45 parameters for age-based selectivity, length-based retention, and time blocking of the fleets and the surveys; 163 recruitment deviations (including 30 pre-model deviations); and 10 forecast recruitment deviations which were fixed at 0 (Table \@ref(tab:parameters)).

The stock-recruitment relationship follows a Beverton--Holt parameterization with steepness ($h$) fixed at `r model[["parameters"]] |> dplyr::filter(grepl("steep",Label)) |> dplyr::pull(Value) |> sprintf(fmt = "%0.2f")` due to the largely one-way trip nature of the time series during the period with good data collections and the high degree of confounding between equilibrium recruitment, $M$, and $h$. Likelihood profiles for $h$ in past `r spp` assessments suggest that there is little information in the data to determine $h$. The use of a fixed value under estimates the uncertainty in $MSY$ and equilibrium yield. However, the importance of this reduced uncertainty is somewhat reduced because both and $F$ and $SB_{proxy}$ are used for management rather than $MSY$.

The standard deviation of recruitment deviates remained fixed at 1.4 and was not iteratively tuned when running the model. Model results suggest that recruitment may be more variable but since 2019 the value has not been allowed to be higher than 1.4.

Maturity-at-length and length-weight parameters also remained fixed at the values that were externally estimated in 2019 and used in the 2019 benchmark assessment [@haltuch_status_2019b] (Figures \@ref(fig:maturity) and \@ref(fig:weight-at-length)). The fecundity relationship was not updated here or in 2019 and is assumed equal to female weight-at-length.

Selectivity curves remained dome shaped for all fleets within the model. The dome-shaped curves are appropriate given that older `r spp` are often found in deeper waters and may move into areas that limit their availability to fishing gear. The descending limb of dome-shaped age selectivity in the fixed-gear fleet remained fixed at the value used in the 2019 benchmark assessment, which was based on the results of likelihood profiles [@haltuch_status_2019b].
