## Base Model Results

### Base Model Selection

Sources of structural uncertainty in this assessment remain largely the same as the previous assessment because this is an `r document_type` rather than a benchmark assessment. Model selection processes were limited to fixing the two parameters related to selectivity and retention that were consistently estimated at their bounds during the bridging analysis (see Section \@ref(model-changes-from-the-last-assessment)).

In reality, un-modeled spatiotemporal variation in $M$, growth, and movement because of predation, availability of food resources, or environmental factors may, to an unknown degree, impact `r spp` and the perception of stock size and status. Potential shifts in the spatial distribution of `r spp` in response to changes in density outside the waters of the California Current or climate impacts could substantially reduce our ability to model and predict current and future trends. However, this degree of complexity is beyond the information content of the currently available data but efforts to synthesize existing data for Northeast Pacific `r spp` with the aim of stock-wide modeling are underway. Until then, residual patterns in the length data may be present due to un-modeled time-varying processes.

### Parameter Estimates

<!-- M, R_0, and growth -->
Estimates of key parameters include 
female $M$ =
`r text_parameter(model, "NatM_uniform_Fem_GP_1", "%.3f")` yr$^{-1}$, 
male $M$ =
`r text_parameter(model, "NatM_uniform_Mal_GP_1", "%.3f")` yr$^{-1}$, and
$R_0$ =
`r text_parameter(model, "SR_LN\\(R0\\)", "%.3f")` (Table \@ref(tab:parameters)). 
Females were estimated to grow larger than males with female length-at-age
`r inputs[["ctl"]][["Growth_Age_for_L2"]]`
(the second reference age) equal to 
`r text_parameter(model, "L_at_Amax_Fem_GP_1", "%.1f")` cm compared to
`r text_parameter(model, "L_at_Amax_Mal_GP_1", "%.1f")` cm for males (Figure \@ref(fig:growth)). Yet, the sexes were estimated to have relatively similar growth rates 
(`r text_parameter(model, "VonBert_K_Fem_GP_1", "%.3f")` yr$^{-1}$ for females compared to
`r text_parameter(model, "VonBert_K_Mal_GP_1", "%.3f")` yr$^{-1}$ for males).

Age-based selectivity was estimated as dome shaped for all fishery and survey fleets in the model. <!-- Fleet 1 --> Sex-specific selectivity for the fixed-gear fleet was estimated to be higher for female fish compared to male fish. The age of peak female selectivity for the for the fixed-gear fleet was fixed at
`r text_parameter(model, "Age.+peak_FIX.+\\)$", "%.0f")` for the historical period between `r startyr`--1996
but varied with time, decreasing in 1997 to
`r text_parameter(model, "Age.+peak_FIX.+1997$", "%.0f")`,
increasing in 2003 to
`r text_parameter(model, "Age.+peak_FIX.+2003$", "%.0f")`, and
decreasing in 2011 to
`r text_parameter(model, "Age.+peak_FIX.+2011$", "%.0f")`.
The peak of the female selectivity curve for the fixed-gear fleet was further to the right than all other estimated selectivity peaks (Figure \@ref(fig:sel02-multiple-fleets-age1)) indicating that this fleet selected older females compared to the other fleets. This was not surprising given that only 21 fish ages 0--1 were identified in samples taken from the fixed-gear fleet. 

This `r document_type` added recent, 2020--2021, \gls{wcgop} data (discard rates, mean weights, and lengths) to better inform 2019--`r endyr` retention. During model bridging, the retention curve for the fixed-gear fleet estimated the peak size at the lower bound of 10 cm, a size where there is little to no selectivity, and it was decided to fix this parameter at the previous estimate of `r round(model$parameters[model$parameters$Label == "Retain_L_infl_FIX(1)_BLK2repl_2019", "Value"],1)`. The 2019--`r endyr` fixed-gear retention curve suggests that a decreased proportion (< 1.0) of fish were retained across all sizes relative to the previous 2011--2019 time block (Figures \@ref(fig:retention)--\@ref(fig:sel09-len-flt1sex2)).

<!-- Fleet 2 -->
A single, rather than sex-specific, selectivity curve was estimated for the trawl fleet with four fixed parameters, one estimated time-invariant parameter, and one time-varying parameter. The trawl fleet selects the largest range of ages compared to all other fleets in the model. The initial age of peak selectivity for the for the trawl fleet was fixed at `r text_parameter(model, "Age.+peak_TWL.+\\)$", "%.1f")`. The time-varying width of the descending limb has been fixed for the early period (`r startyr`--1981) since the 2019 model. This `r document_type` also fixed it at the upper bound (`r text_parameter(model, "desc.+TWL.+2011$", "%.1f")`) in the terminal time block (2011--`r endyr`) because it was consistently estimated at the bound during the bridging analyses. As time progressed in the model period, the estimate of the descending limb of the selectivity curve increased across time blocks indicating the selection of an increasing proportion of older fish with time. The retention curve shifted rightward in the final time block (2019--2022) compared to the previous time block (2011--2018) (Figures \@ref(fig:retention), \@ref(fig:sel09-len-flt2sex1), and \@ref(fig:sel09-len-flt2sex2)).

<!-- Fleet 3 Environmental Index -->
<!-- NA -->

<!-- Fleet 4 -->
Selectivity for the \gls{s-tri} indicates that this survey selected the least amount of older fish relative to the other surveys and fleets, descending to a near-zero selectivity at about the same age, age 4--5, as the peak in the fixed-gear fleet (Figure \@ref(fig:sel02-multiple-fleets-age1)). Selectivity was sex-specific for this survey, with male selectivity being
`r model[["parameters"]] |> dplyr::filter(grepl("Age.+MaleatD.+_A", Label)) |> dplyr::mutate(Value = exp(Value) * 100) |> dplyr::pull(Value) |> sprintf(fmt = "%.0f")`
percent of female selectivity at age zero and
`r model[["parameters"]] |> dplyr::filter(grepl("Age.+MaleatM.+_A", Label)) |> dplyr::mutate(Value = exp(Value) * 100) |> dplyr::pull(Value) |> sprintf(fmt = "%.0f")`
percent of female selectivity at the maximum age (Figure \@ref(fig:sel02-multiple-fleets-age1)).
Although, female selectivity at approximately 5 years and older was small in its own right.

<!-- Fleet 5 -->
<!-- Fleet 6 -->
The time- and sex-invariant selectivities for the slope surveys were similar to estimates from previous models, with the \gls{s-nslope} selecting more older fish than any other survey and the \gls{s-aslope} selecting fish at a younger age than the \gls{s-nslope} (Figure \@ref(fig:sel02-multiple-fleets-age1)). `r Spp` abundance is correlated with temperature and depth, and thus, the higher selectivities of the slope surveys may be a combination of availability and gear selectivity rather than just gear selectivity alone. The width of the descending limb for both slope surveys was poorly estimated, reflected in the high estimates of uncertainty for these parameters.

<!-- Fleet 7 -->
The \gls{s-wcgbt} was estimated to select the youngest fish of all the fleets and surveys (peak selectivity at age `r text_parameter(model, "Age.+_peak_NWCBO", "%.2f")`) and a similar amount of older fish as the \gls{s-aslope} (Figure \@ref(fig:sel02-multiple-fleets-age1)). The higher selection of young fish in the \gls{s-wcgbt} compared to the current fleets increases the potential for the \gls{s-wcgbt} to provide information about strong year classes sooner than the fisheries. 

<!-- A note about poor model configuration -->
A number of issues were noticed when reviewing the estimation of selectivity and retention in this `r document_type`. Across all fleets, there were a number of selectivity parameters that were estimated with high uncertainty that may indicate a lack of information in the data to estimate these parameters. During this assessment, some of these difficult to estimate parameters were fixed a their bounds. These general behaviors were also encountered in the 2019 assessment and resulted in a number of selectivity parameters being fixed during model development due to poor estimation behavior at that time. These issues indicate that selectivity may be overparameterized. The next benchmark assessment should explore simplifying selectivity as well as explore alternative parameterizations. To better understand the impact of estimating poorly informed selectivity parameters, a sensitivity is included in Section \@ref(sensitivity-analyses) that fixes selectivity parameters with high uncertainty at their estimates but the model results are largely the same.

<!-- A note about poor model configuration 
Despite the small number of samples at young ages from this fleet, the model parameterization includes the estimation of the male offset at age zero. This parameter is noted in the \gls{ss3} manual [@methot_stock_2013] as being difficult to estimate and often poorly informed by the data. Best practices suggests that it should be fixed at zero, though fixing it at zero led to almost no differences in parameter estimates (Figure \@ref(fig:sensitivity-3-compare1)). At the peak, males were selected about
`r model[["parameters"]] |> dplyr::filter(grepl("Age.+MaleatD.+_FIX", Label)) |> dplyr::mutate(Value = exp(Value) * 100) |> dplyr::pull(Value) |> sprintf(fmt = "%2.0f")`
percent as much as females in this fishery.
-->

<!-- Catchability -->
```{r q-estimates}
q_parameters <- text_parameter(model, "LnQ", "%.9f") |> as.numeric() |> exp()
q_text_range <- paste(round(range(q_parameters), 2), collapse = "--")
q_which_fleet_max <- recode_fleet_text(as.numeric(gsub(
  ".+\\(([0-9]+)\\)(.{0,})",
  "\\1",
  text_parameter(model, "LnQ", "%s", Label)
)[which.max(q_parameters)]))
q_4_blk <- exp(as.numeric(text_parameter(model, "LnQ.+4.+BLK", "%.2f")))
```
Estimates of catchability for the trawl surveys ranged from `r q_text_range` with the `r q_which_fleet_max` having the highest catchability across surveys. However, the catchability for this survey was estimated to have decreased in 1995 to `r round(q_4_blk,2)`. The input data for all historical surveys were not altered for this assessment and it could be that the estimates of abundance for the \gls{s-tri} are inflated relative to its footprint if the survey was projected to the entire California Current rather than just outside its spatial footprint. The environmental survey had the highest estimate of additional variance needed to fit the data of all the indices used to fit the model (Table \@ref(tab:parameters)). A sensitivity is included (see Section \@ref(sensitivity-analyses)) where the added variance for the \gls{s-wcgbt} was turned on, in which it was estimated to be non-zero, unlike in 2019 and 2021. In this sensitivity, the added variance allowed to model to not fit the final two survey data points (2021 and 2022) that show a sharp increase relative to the 2019 data point.

<!-- recruitment -->
Annual recruitment deviations (Table \@ref(tab:parameters); Figure \@ref(fig:recruits)) was estimated to be the highest in the following ten years:
`r model[["parameters"]] |> dplyr::filter(grepl("Dev", Label)) |> dplyr::arrange(-Value) |> dplyr::slice_head(n = 10) |> tidyr::separate_wider_delim(cols = Label, delim = "_", names = c("Period", "Type", "Year")) |> dplyr::pull(Year) |> glue::glue_collapse(", ", last = ", and ")`, in order from largest to smallest. These estimates are informed by the \gls{s-wcgbt} 2021-2022 data that had sharp increases in the number of age-0 and age-1 fish being observed.  Additionally, the fishery has reported encountering large numbers of small `r spp` in the last couple of years. While there seems to be strong information that there may be multiple strong recruitments in recent years additional observations of these fish, as they mature and enter the fishery, will better inform the magnitude of these recruitments. The fourth largest estimated recruitment deviation in time series occurred in the mid-1960s. The exact year of this large recruitment is uncertain with the year of occurrence tending to shift to any year between 1964 and 1966 depending on the parameterization of the model.
The smallest ten recruitment events, which are harder to estimate than large events, occurred in the following years:
`r model[["parameters"]] |> dplyr::filter(grepl("Dev", Label)) |> dplyr::arrange(Value) |> dplyr::slice_head(n = 10) |> tidyr::separate_wider_delim(cols = Label, delim = "_", names = c("Period", "Type", "Year")) |> dplyr::pull(Year) |> glue::glue_collapse(", ", last = ", and ")`. The bias adjustment ramp was left the same as the previous assessment except for extending the right limb by two years (Figure \@ref(fig:bias-adjust)). The suggested ramp is based on the environmental time series being informative about recruitment where we chose to retain the setting from previous assessments that implement the ramp with the onset of biological age samples rather than the start of the environmental time series. Recruitment is up to the terminal year of the model because the survey selects such young fish and is based on the spawner--recruit curve in the forecast period (Figure \@ref(fig:bh-curve)).


### Fits to the Data

<!-- indices -->
Fits to the environmental time series were noisy, as they have been in previous assessments. The estimated index is essentially a flat line until the most recent years, where there are sharp increases followed by a prompt return to zero (Figure \@ref(fig:index2-cpuefit-3)). The estimated added standard deviation was `r text_parameter(model, "extra.+ENV", "%f")`, and thus, the environmental time series provided limited information regarding historical recruitment. In 2019, this added variance parameter was estimated at 0.73 suggesting that the environmental index has lost some prediction power since the last benchmark assessment.

Fits to the historical surveys were similar to the last assessment. The \gls{s-tri} data showed an increasing trend in the 2000s, though the model failed to fit the high estimates of abundance in the early 2000s and is even below the lower limit of the estimated added variance (Figure \@ref(fig:index2-cpuefit-4)). Fits to the \gls{s-aslope} suggest a slight decreasing trend during the late 1990s followed by a small increase into the early 2000s (Figure \@ref(fig:index2-cpuefit-5)). There was no estimated trend in the \gls{s-nslope}, as might be expected for such short time series (Figure \@ref(fig:index2-cpuefit-6)).

The base model fit the decline, subsequent stabilization, and terminal increase in the \gls{s-wcgbt} well until the two most recent years of the survey (Figure \@ref(fig:index2-cpuefit-7)). The recent estimates were below the data providing some justification for estimating an additional variance parameter (see Section \@ref(sensitivity-analyses)), though this was not included in the base model.

<!-- lengths -->
Of all the length data used to fit the model, the model fit the discard lengths from the fixed-gear fishery the best (Figure \@ref(fig:comp-lenfit--aggregated-across-time)). The fits to the discarded lengths from the trawl fleet were not as good as they were for the fixed-gear fleet (`r subset(information_fit_figures, partition == 1)[["label_text_group"]][[1]]`). Where, large residuals were only present in the fits to the discarded fixed-gear lengths in years prior to 2007 (`r subset(information_fit_figures, partition == 1 & type == "length" & fleet_number == 1)[["label_text_group_fleet"]][[1]]`). Where similar magnitudes of underfitting the data are present for the trawl fleet for almost all recent years since 2014 (`r subset(information_fit_figures, partition == 1 & type == "length" & fleet_number == 2)[["label_text_group_fleet"]][[1]]`). The expected distribution of discarded lengths from the trawl fishery was shifted to the left of the observed lengths for the recent years, a pattern largely not seen in years prior to 2014. The 2021 update assessment [@Kapur:2021:SSA] had similar fits to the annual discarded lengths for both fleets.

Some of the worst fits to the length data were for the large numbers of small, i.e., 20--30 cm, fish in the \gls{s-wcgbt} (`r subset(information_fit_figures, partition == 0 & type == "length")[["label_text_group"]][[1]]`). These small, unsexed fish are almost always under fit relative to larger, unsexed fish because larger fish have a higher tendency of being sexed and thus the distribution of the sampled, unsexed fish will not represent the true population. In some years, the fits to the sexed data from the \gls{s-wcgbt} were quite good (`r subset(information_fit_figures, partition == 0 & type == "length" & fleet_number == 7)[["label_text_group_fleet"]][[1]]`) and match the bimodal distribution of lengths (e.g., 2015 and 2021) found in the data (`r subset(information_comp_figures, partition == 0 & type == "length" & fleet_number == 7)[["label_text_group_fleet"]][[1]]`). Other years, (e.g., 2022) the underfitting of the small, unsexed fish was also seen in the sexed fish.

<!-- ages -->
Underfitting of some younger ages and overfitting of very old males was common in all fleets and surveys except the \gls{s-aslope} (Figure \@ref(fig:comp-agefit--aggregated-across-time)). These same patterns were present in the 2021 update assessment [@Kapur:2021:SSA] but the latter pattern was not present in the 2019 benchmark assessment [@haltuch_status_2019b]. The largest residuals in the marginal age compositions were seen in the fits to the age data from the \gls{s-tri} (Figures \@ref(`r paste0("fig:", subset(information_fit_figures, partition == 0 & type == "age")[1, "label"])`)--\@ref(`r paste0("fig:", subset(information_fit_figures, fleet_number == 7 & type == "age")[1, "label"])`)). This was the one fleet where Francis data weighting suggested substantially increasing the weight of these age data well beyond the input sample size but the weight for these data was capped at 1.0, equal to the number of ages. The data for the slope surveys are limited given the short time series and no stark patterns were detected in the residuals. Conditional age-at-length data from the \gls{s-wcgbt} were fit particularly well for lengths less than 60 cm (`r subset(information_fit_figures, fleet_number == 7 & type == "conditional")[["label_text_group"]][[1]]`), noting that 60 cm is approaching the estimated maximum length for females. The expected mean age-at-length generally matched the observed mean age-at-length for sizes less than 60 cm and ages less than 20 years across all years. The expected mean age-at-length, in general, split the observed data points for older, larger fish starting in 2009 but for earlier years, 2003--2008, the expected mean age-at-length was generally higher than the observations. The standard deviation around growth was largest at the ranges of the observed ages\slash lengths. Marginal ages for the \gls{s-wcgbt} were included in the model but were not included in the likelihood (`r subset(information_fit_figures, fleet_number == 7 & type == "age")[["label_text"]][[1]]`).

### Population Trajectory

Spawning biomass, the proxy for spawning output, is estimated to have declined from an unfished equilibrium of
`r text_parameter(model, "S.+_Virgin", "%f", object = "derived_quants", big_mark = ",")` to
approximately 79,000 mt in the 1950s (Table \@ref(tab:timeseries) and Figure \@ref(fig:ts-spawning-biomass)). Biomass quickly turned around, increasing to unfished equilibrium by the mid-1970s, only to come down again to the management target in the early-2000s. Since then, several strong recruitment events (2008, 2013, and 2016) have led to sharp increases in spawning biomass, though spawning biomass remains far from unfished levels at the end of time series (Figure \@ref(fig:ts-relative-spawning-biomass-forecast)). Total biomass largely follows the same trajectory as spawning biomass across the majority of the time series with a distinct departure in the most recent years with total biomass sharply increasing based on the large estimated sizes of the 2020 and 2021 recruitment deviations (Figure \@ref(fig:ts-total-biomass)).
