# Acknowledgments

Many people were instrumental in the successful completion of this assessment update and their contribution is greatly appreciated. This assessment draws heavily on the text and analyses from previous `r spp` assessments and has benefited greatly from the efforts of all authors contributing to those analyses. We are very grateful to all the agers at the Cooperative Ageing Program for their willingness to add reading `r spp` otoliths to their already heavy workload this year at the last minute. Thank you to the \gls{wcgop} staff, Kayleigh Somers and Kate Richardson, for their support providing critical data on fishery retention and discarding practices across time. We would like to acknowledge \gls{nwfsc} Fisheries Resource and Monitoring survey team and their dedication to collecting critical data to support stock assessments. The assessment was greatly improved through the streamlining of data processing tools developed and maintained by the Population Ecology team at the \gls{nwfsc}.
