\clearpage

\hyphenation{ }
\ifx \undefined \bioname      \def \bioname   #1{{{\em #1\/}}}     \fi
\ifx \undefined \booktitle    \def \booktitle #1{{{\em #1}}}       \fi
\ifx \undefined \circled      \def \circled   #1{(#1)}             \fi
\ifx \undefined \degree       \def \degree      {$^o$}             \fi
\ifx \undefined \emph         \def \emph      #1{{{\em #1\/}}}     \fi
\ifx \undefined \Eth          \def \Eth         {D}                \fi
\ifx \undefined \eth          \def \eth         {d}                \fi
\ifx \undefined \flqq         \def \flqq        {\ifmmode \ll \else \leavevmode \raise 0.2ex \hbox{$\scriptscriptstyle \ll $}\fi}\fi
\ifx \undefined \frqq         \def \frqq        {\ifmmode \gg \else \leavevmode \raise 0.2ex \hbox{$\scriptscriptstyle \gg $}\fi}\fi
\ifx \undefined \gene         \def \gene      #1{{{\sf #1}}}       \fi
\ifx \undefined \k            \let \k = \c                         \fi
\ifx \undefined \latinname    \def \latinname #1{{{\em #1\/}}}     \fi
\ifx \undefined \mathbb       \def \mathbb    #1{{\bf #1}}         \fi
\ifx \undefined \mathbf       \def \mathbf    #1{{\bf #1}}         \fi
\ifx \undefined \ocirc        \def \ocirc     #1{{\accent'27#1}}   \fi
\ifx \undefined \pkg          \def \pkg       #1{{{\tt #1}}}       \fi
\ifx \undefined \r            \let \r = \ocirc                     \fi
\ifx \undefined \reg          \def \reg {\circled{R}}              \fi
\ifx \undefined \Thorn        \def \Thorn       {T}                \fi
\ifx \undefined \TM           \def \TM {${}^{\sc TM}$}             \fi
\ifx \undefined \vessel       \def \vessel    #1{{\em #1\/}}       \fi

# References
<!-- If you want the references to appear somewhere before the end, add: -->
<div id="refs"></div>
<!-- where you want it to appear -->
<!-- The following sets the appropriate indentation for the references
  but it cannot be used with bookdown and the make file because it leads
  to a bad pdf.
\noindent
\vspace{-2em}
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
 -->
