\clearpage
# Tables

## Data

**to do**: this section is incomplete, more tables are needed and some can be provided as external csv files

```{r, results = "asis"}
sa4ss::table_format(
  x = model[["timeseries"]] |>
    dplyr::filter(
      Yr >= startyr
    ) |>
    dplyr::select(Year = Yr, dplyr::starts_with("retain(B):")) |>
    dplyr::mutate(
      `Total Landings` = rowSums(dplyr::across(dplyr::starts_with("retain"))),
      dplyr::across(where(is.numeric), round, 1)
    ),
  caption = "Landings (mt) by fleet and the summed coastwide total landings.",
  label = "landings",
  digits = 1,
  align = "l",
  # to do: use a renamer between fleet number and name
  col_names = c("Year", "Fixed Gear", "Trawl", "Total Landings")
)
```

<!-- to do: provide this as a csv -->
```{r tab-data-strata, results = "asis", eval = TRUE}
sa4ss::table_format(
  x = strata |>
    dplyr::select(-name) |>
    dplyr::relocate(area, .after = dplyr::last_col()),
  caption = paste(
    "The stratification used to estimate design-based indices of abundance",
    "and to expand the survey composition data."
  ),
  longtable = FALSE,
  escape = FALSE,
  label = "data-strata",
  col_names_align = "l",
  align = "r",
  col_names = c(
    "Shallow Depth",
    "Deep Depth",
    "South\\ Latitude",
    "North\\ Latitude",
    "Area (km$^2$)"
  )
)
```

\include{52tables/data-survey-n.tex}

## Model Results

**to do** missing model set up table

### Estimated Parameters

```{r table-parameters, results = "asis"}
# Find sigma R
sigma_r <- model[["parameters"]] %>%
  dplyr::filter(grepl("sigma", ignore.case = TRUE, Label)) %>%
  dplyr::pull(Value)
# to do - Could format the names
recode_parameters <- function(x) {
  x |>
    gsub(pattern = "(.+)_(Fem)(.+)", replacement = "\\1 (female)") |>
    gsub(pattern = "(.+)_(Mal)(.+)", replacement = "\\1 (male)") |>
    gsub(pattern = "NatM", replacement = "$M$") |>
    gsub(pattern = "_base|_uniform", replacement = "") |>
    gsub(pattern = "_I.+Age_", replacement = " age ") |>
    gsub(pattern = "_BLK[0-9]+repl", replacement = "") |>
    gsub(pattern = "_([A-Za-z]+)\\([0-9]+\\)", replacement = "_\\1") |>
    gsub(pattern = "_logit|_DblN|_se|Mort|", replacement = "") |>
    gsub(pattern = "_at_", replacement = "-at-") |>
    gsub(pattern = "Retain", replacement = "Ret") |>
    gsub(pattern = "AgeSel", replacement = "Age") |>
    # Remove the following if more than 1 area
    gsub(pattern = "_GP_1", replacement = "")
}
model[["parameters"]] %>%
  dplyr::select(
    Label,
    Value,
    Phase,
    Min,
    Max,
    Pr_type,
    Prior,
    Parm_StDev,
    Pr_SD,
    Status
  ) %>%
  dplyr::mutate(
    Label = recode_parameters(Label),
    Value = ifelse(
      grepl("Wtlen[_]{0,}1", Label),
      sprintf("%.3e", Value),
      sprintf("%8.3f", Value)
    ),
    Min = sprintf("%8.3f", Min),
    Max = sprintf("%8.3f", Max),
    Status = dplyr::case_when(
      is.na(Status) ~ "-",
      Status == "act" ~ "-",
      TRUE ~ Status
    ),
    SD = ifelse(is.na(Parm_StDev), "-", sprintf("%2.2f", Parm_StDev)),
    Prior = dplyr::case_when(
      Pr_type == "Log_Norm" ~ sprintf("lnN(%2.3f, %2.3f)", exp(Prior), Pr_SD),
      Pr_type == "No_prior" ~ "-",
      Pr_type == "Full_Beta" ~ sprintf("beta(%2.3f, %2.3f)", Prior, Pr_SD),
      Pr_type == "dev" ~ sprintf("N(0.000 %2.3f)", sigma_r),
      TRUE ~ Pr_type
    )
  ) %>%
  dplyr::select(Label, Value, SD, Phase, Prior, Min. = Min, Max. = Max, Status) %>%
  kableExtra::kbl(
    align = "lrrrrrrr",
    row.names = FALSE,
    longtable = TRUE,
    booktabs = TRUE,
    format = "latex",
    caption = "Parameter estimates, estimation phase, parameter bounds, estimation status, estimated standard deviation (SD), prior information [distribution(mean, SD)] used in the base model.",
    label = "parameters"
  )
```

```{r tables-likelihoods, results = "asis"}
table_likelihoods(model)
```

```{r tables-weights, results = "asis"}
dplyr::bind_rows(
  .id = "Type",
  Length = model[["Length_Comp_Fit_Summary"]],
  Age = model[["Age_Comp_Fit_Summary"]]
) |>
  dplyr::mutate(
    Fleet = recode_fleet_text(as.numeric(Fleet))
  ) |>
  dplyr::select(Type, Fleet, "Francis" = Curr_Var_Adj) |>
  dplyr::mutate(Francis = sprintf("%.2f", Francis)) |>
  kableExtra::kbl(
    escape = FALSE,
    row.names = FALSE,
    longtable = FALSE,
    booktabs = TRUE,
    label = "composition-weight",
    caption = "Data weightings applied to length and age compositions according to the `Francis' method.",
    format = "latex"
  )
```

```{r tables-time-series, results = "asis"}
ts <- utils::read.csv(fs::path(model_location, "tables", "TimeSeries.csv"))
ts[, c(2:4, 6:7)] <- round(ts[, c(2:4, 6:7)],0)
ts[, c(5, 8:9)] <- round(ts[, c(5, 8:9)],3)
col_names <- c("Year", "Total Biomass (mt)", "Spawning Biomass (mt)", "Total Biomass Age 4+ (mt)", "Fraction Unfished", "Age-0 Recruits", "Total Mortality (mt)", "(1-SPR)/(1-SPR45%)", "Exploitation Rate")
sa4ss::table_format(
  x = ts,
  caption = "Time series of population estimates from the base model.",
  label = "timeseries",
  align = "l",
  col_names = col_names,
  custom_width = TRUE,
  col_to_adjust = c(2:9),
  width = rep("1.4cm", 8)
)

#sa4ss::read_child(fs::path(model_location, "tables", "TimeSeries.tex"))
```

### Sensitivity and Retrospective Analyses

```{r tables-sensitivity, results = "asis"}
tab <- utils::read.csv(fs::dir_ls(
  dirname(model_location),
  regexp = "sensitivity_table.csv",
  recurse = TRUE
), check.names = FALSE)
colnames(tab)[1:2] <- c("Likelihood or Parameter", "Base Model")
sensitivity_groups <- purrr::map(
  c(
    "base|index|estimate|bridging|Fix",
    "base|recruitment|survey",
    "base|mortality|marginal|tune"
  ),
  .f = \(x) grep(
    pattern = x,
    x = colnames(tab),
    ignore.case = TRUE
  )
)
tab[,-1] <- round(tab[,-1], 2)
tab[,1] <- c(
                   "Total Likelihood",
                   "Survey Likelihood", 
                   "Discard Likelihood", 
                   "Length Likelihood",
                   "Age Likelihood",
                   "Recruitment Likelihood", 
                   "Forecast Rec. Likelihood",
                   "Prior Likelihood",
                   "Parameter Devs. Likelihood",
                   "R0", "SB0", "SB 2023", "Fraction Unfished 2023",
                   "Yield at SPR", "Steepness", 
                   "M (female)", "Lmin (female)", "Lmax (female)", "k (female)", "CV1 (female)", "CV2 (female)",
                   "M (male)", "Lmin (male)", "Lmax (male)", "k (male)", "CV1 (male)", "CV2 (male)")
for(i in 1:3) {
  out <- sa4ss::table_format(
  x = purrr::map(sensitivity_groups, .f = \(x) tab[c(1, x)])[[i]],
  caption = glue::glue("The total and likelihood contribution by data type and parameter estimates for the sensitivity group {1:3}.")[i],
  label = glue::glue("sensitivity-ests-{1:3}")[i],
  align = "r"
)
cat(out, sep = "/n")
}
```

```{r tables-retro, results = "asis"}
file_retro <- fs::dir_ls(
  dirname(model_location),
  regexp = "mohnsrho.tex",
  recurse = TRUE
)
stopifnot(length(file_retro) == 1)
sa4ss::read_child(
  fs::dir_ls(dirname(model_location), regexp = "mohnsrho.tex", recurse = TRUE)
)

csv_retro <- fs::dir_ls(
  dirname(model_location),
  regexp = "retro_quant_table.csv",
  recurse = TRUE
)
tab <- utils::read.csv(csv_retro)
tab[,-1] <- round(tab[,-1], 2)
colnames(tab) <- c("Likelihood or Parameter", "Base Model", paste("Retro", -1:-5))
tab[,1] <- c(
                   "Total Likelihood",
                   "Survey Likelihood", 
                   "Discard Likelihood", 
                   "Length Likelihood",
                   "Age Likelihood",
                   "Recruitment Likelihood", 
                   "Forecast Rec. Likelihood",
                   "Prior Likelihood",
                   "Parameter Devs. Likelihood",
                   "R0", "SB0", "SB 2023", "Fraction Unfished 2023",
                   "Yield at SPR", "Steepness", 
                   "M (female)", "Lmin (female)", "Lmax (female)", "k (female)", "CV1 (female)", "CV2 (female)",
                   "M (male)", "Lmin (male)", "Lmax (male)", "k (male)", "CV1 (male)", "CV2 (male)")
sa4ss::table_format(
  x = tab,
  caption = "The total and likelihood contribution by data type and parameter estimates for the base model and the retrospective data peels.",
  label = "retro-ests",
  align = "l"
)
```

## Reference Points and Projections

```{r, tables-projection, results = "asis"}
# Yes I know this code will likely make your eye twitch... sorry
tab <- cbind(utils::read.csv(here::here("data-processed", "harvest_spex.csv")) |>
  dplyr::filter(AREA_NAME == "CW" & YEAR >= 2023 & PECIFICATION_TYPE == "OFL") |>
  dplyr::reframe(
    Year = c(YEAR, 2025:2034),
    `Adopted OFL` = c(round(VAL, 1), rep("-", 10))
  ),
  utils::read.csv(here::here("data-processed", "harvest_spex.csv")) |>
  dplyr::filter(AREA_NAME == "CW" & YEAR >= 2023 & PECIFICATION_TYPE == "ACL") |>
  dplyr::reframe(
    `Adopted ACL` = c(round(VAL, 1), rep("-", 10))
  ))
  
x <- model[["timeseries"]] |>
  dplyr::reframe(
    Year = Yr,
    `Assumed Removals` = round(rowSums(dplyr::across(dplyr::starts_with("dead(B)"))), 1),
    ABC = round(rowSums(dplyr::across(dplyr::starts_with("dead(B)"))), 1),
    `Spawning Biomass` = round(SpawnBio, 1),
    `Fraction Unfished` = round(`Spawning Biomass`/`Spawning Biomass`[1],3)
  ) |>
  dplyr::filter(Year > endyr)

x[x$Year > 2024, "Assumed Removals"] <- "-"
x[x$Year %in% 2023:2024, "ABC"] <- "-"
OFL <- round(model$derived_quants[model$derived_quants$Label %in% paste0("OFLCatch_", 2023:2034), "Value"], 1) 
OFL[1:2] <- "-"
out <- cbind(tab, x[, "Assumed Removals"], OFL, x[,c(-1, -2)])
colnames(out)[4] <- "Assumed Removals"
sa4ss::table_format(
  x = out,
  caption = "The adopted OFL (mt), ACL (mt), and assumed removals (mt) in 2023--24 and the projected OFL (mt), ABC (mt), spawning biomass, and fraction unfished for 2025--2034.",
  label = "model-projection",
  align = "l"
)
```

```{r results = "asis"}
es_text <- readLines(
  fs::path(model_location, "tables", "e_ReferencePoints_ES.tex")
) |>
  purrr::map_chr(.f = \(x) gsub("(tab:reference)ES", "\\1", x))
cat(es_text, sep = "\n")
```
