

\floatplacement{figure}{H}

# Figures

## Data

### Summary

```{r, figures-data-summary, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "data_plot.png"
  ),
  caption = "Summary of data sources used in the base model.",
  alt_caption = "Tabular information for this figure can be found in the data file.",
  height = 80,
  label = "data-summary"
)
```

### Fishery-Dependent Data

```{r, figures-data-landings, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "catch2 landings stacked.png"
  ),
  caption = "Landings (mt) by year from the fixed gear (blue) and trawl (red) fleets.",
  alt_caption = "See Table 1 for the time series shown in this figure.",
  label = "data-landings"
)
```

```{r figures-fishery-dependent-data, results = "asis"}
ignore <- information_discard_figures |>
  dplyr::select(filein, label, caption) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "See Report.sso for the time series of discard rates."
  )

ignore <- information_comp_figures |>
  dplyr::filter(fleet_number %in% 1:2) |>
  dplyr::select(filein, label, caption) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "See Report.sso for the time series of discard compositions."
  )
```

### Fishery-Independent Data

```{r figures-data-survey-wcgbt, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(
    here::here(),
    figure_dir,
    "data_survey_wcgbt_proportion-by-depth.png"
  ),
  caption = glue::glue("The proportion of tows that observe {spp} out of all tows performed within a given range of depths m sampled for the \\glsentrylong{{s-wcgbt}}."),
  alt_caption = glue::glue("Approximately 25 percent of tows include {spp} at the shallowest depths sampled between 50 m and 100 m with the percent positive tows increasing to 75 percent by 300 m. The highest percent positive tows occurs between 950 m and 1050 m with {spp} observed in greater than 95 percent of tows. The percent positive tows slowly declines to approximately 60 percent at the maximum depth sampled which was 1280 m."),
  label = "data-survey-wcgbt-proportion-by-depth"
)

sa4ss::add_figure(
  filein = fs::path(
    here::here(),
    figure_dir,
    "data_survey_wcgbt_presence-by-lat.png"
  ),
  caption = glue::glue("The proportion of tows that observe {spp} out of all tows performed within a given range of latitudes (decimal degrees) in the \\glsentrylong{{s-wcgbt}}."),
  alt_caption = glue::glue("Approximately 70--75 percent of tows include {spp} in Oregon and Washington. In California north of Point Conception approximately 70 percent of the tows include {spp} except around Point Reyes where the percentage declines to between 60--70 percent. South of Point Conception in California 25--45 percent of tows include {spp}."),
  label = "data-survey-wcgbt-proportion-by-latitude"
)

sa4ss::add_figure(
  fs::path(figures_location, "qq.png"),
  caption = "Quantile-quantile plot for the presence\\slash absence (purple) and rate (yellow) components of a delta model fit to abundance data from the \\glsentrylong{s-wcgbt} where the rate component assumed a gamma distribution.",
  alt_caption = "Points largely fall on the 1:1 line.",
  label = "qq"
)

sa4ss::add_figure(
  filein = fs::dir_ls(
    regexp = "index1_.+NWCBO|index1.+cpuedata_WCGBT",
    path = fs::path(model_location, "plots")
  ),
  caption = "Annual relative index of abundance for the \\glsentrylong{s-wcgbt}.",
  alt_caption = "See Report.sso for the time series.",
  label = "data-survey-wcgbt-index"
)

sa4ss::add_figure(
  filein = fs::path(
    here::here(),
   figure_dir,
    "data_survey_wcgbt_young-length-by-year.png"
  ),
  caption = "The length distribution of age-0 (upper panel) and age-1 (lower panel) fish by survey pass (colors) across years sampled by the \\glsentrylong{s-wcgbt}. Blue dots indicate the lengths observed for each age and by pass.",
  alt_caption = "The distribution of lengths of age-0 fish generally 30 cm or less with the majority of age-0 fish being observed during pass 2 of the survey. Age-0 fish generally range between 30--45 cm in size with pass 2 observing larger age-1 fish compared to pass 1. Age-1 fish observed in 2021 and 2022 have a wide distribution of observed sizes between 25--45 cm.",
  label = "data-survey-wcgbt-young-length-by-year"
)

# sa4ss::add_figure(
#   filein = fs::path(
#     here::here(),
#     figure_dir,
#     "data_survey_wcgbt_sex-by-depth.png"
#   ),
#   caption = glue::glue("The proportion of {spp} by sex observed by the \\glsentrylong{{s-wcgbt}} across depths sampled.",
#   alt_caption = glue::glue("Observations of female {spp} are 50 percent or slightly greater between 150--400 m with males being observed greater than 50 percent of the tows between 400--1050 m. At the deepest depths sampled between 1050--1280 m females are observed in greater than 50 percent of the tows."),
#   label = "data-survey-wcgbt-sex-by-depth"
# )

ignore <- information_comp_figures |>
  dplyr::filter(fleet_number == 7) |>
  dplyr::select(filein, label, caption) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "Except for 2007 most large residuals are for young fish."
  )

sa4ss::add_figure(
  filein = fs::dir_ls(
    regexp = "index1_cpuedata.+[Ee][Nn][Vv]",
    path = fs::path(model_location, "plots")
  ),
  caption = "Annual relative index of abundance for the environmental index.",
  alt_caption = "See Report.sso for the time series.",
  label = "data-survey-env-index"
)
```

## Model Results

### Bridging

```{r figures-bridging, results = "asis"}
ignore <- fs::dir_ls(
  fs::path(dirname(model_location), "bridging"),
  type = "file",
  regex = "compare1_|compare3_|s_index5|flt7"
) |>
  tibble::as_tibble_col(column_name = "filein") |>
  dplyr::mutate(
    label = paste(
      "bridging",
      gsub("([0-9]+-)([a-z0-9]+)_(.+)(\\.png)", "\\1\\2", basename(filein)),
      sep = "-"
    ),
    type = dplyr::case_when(
      grepl("compare[1-2]_", basename(filein)) ~ "Spawning biomass",
      grepl("compare[3-4]_", basename(filein)) ~ "Fraction unfished",
      grepl("compare13_", basename(filein)) ~ "Recent survey"
    ),
    caption = glue::glue(
      "{type} across several steps towards creating the base model from the previous assessment model."
    )
  ) |>
    dplyr::select(filein, caption, label) |>
    purrr::pmap(
      .f = sa4ss::add_figure,
      alt_caption = "Models followed similar trajectories after being tuned."
    )
```

### Estimated Biology

```{r figures-biology, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "bio6_maturity.png"
  ),
  caption = "Maturity at length.",
  alt_caption = "Fish are 50 percent mature at 55 cm.",
  label = "maturity"
)
sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "bio5_weightatsize.png"
  ),
  caption = "Weight-length relationship.",
  alt_caption = "Mean weight exponentially increases after 40 cm.",
  label = "weight-at-length"
)

sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "bio1_sizeatage.png
"
  ),
  caption = "Length at age in the beginning of the year in the ending year of the model. Shaded area indicates 95\\% distribution of length at age around estimated growth curve.",
  alt_caption = "Maximum length (60 cm) asymptotes at a very young age.",
  label = "growth"
)
```

### Estimated Selectivity

```{r figures-retention, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "selectivity.png"
  ),
  caption = "Estimated selectivity at age by fleet, time block, and sex (female = solid; male = dashed).",
  alt_caption = "See Report.sso for time series of selectivity and retention.",
  label = "sel02-multiple-fleets-age1",
  height = 90
)

sa4ss::add_figure(
  filein = fs::path(
    here::here(),
    figure_dir,
    "retention.png"
  ),
  height = 70,
  caption = "Fleet-specific estimated retention by time block.",
  alt_caption = "See Report.sso for time series of selectivity and retention.",
  label = "retention"
)

 # <!-- Retention -->
ignore <- fs::dir_ls(
  path = fs::path(model_location, "plots"),
  regex = "sel[0-9]+_len_flt[12]"
) |>
  tibble::as_tibble_col(column_name = "filein") |>
  dplyr::mutate(
    sex = ifelse(grepl("sex1", basename(filein)), "females", "males"),
    fleet_numeric = as.numeric(gsub(".+flt([0-9]+)sex.+", "\\1", filein)),
    fleet = recode_fleet_text(fleet_numeric),
    caption = glue::glue("Estimated retention and discard mortality for {sex} for the {fleet}."),
    label = gsub(pattern = "_", "-", gsub("\\.png", "", basename(filein)))
  ) |>
  dplyr::select(filein, caption, label) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "See Report.sso for time series of retention."
  )

#ignore <- fs::dir_ls(
#  path = fs::path(model_location, "plots"),
#  regex = "sel05.+flt[2]"
#) |>
#  tibble::as_tibble_col(column_name = "filein") |>
#  dplyr::mutate(
#    sex = ifelse(grepl("sex1", basename(filein)), "females", "males"),
#    fleet_numeric = as.numeric(gsub(".+flt([0-9]+)sex.+", "\\1", filein)),
#    fleet = recode_fleet_text(fleet_numeric),
#    caption = glue::glue("Estimated time-varying retention and discard mortality for {sex} for the {fleet}."),
#    label = gsub(pattern = "_", "-", gsub("\\.png", "", basename(filein)))
#  ) |>
#  dplyr::select(filein, caption, label) |>
#  purrr::pmap(.f = sa4ss::add_figure)
```

### Estimated Recruitment

```{r, figures-recruitment, results = "asis"}
sa4ss::add_figure(
  filein = file.path(model_location, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"),
  caption = "Estimated time series of age-0 recruits (1000s).",
  alt_caption = "See the time-series table for tabular data.",
  label = "recruits"
)
sa4ss::add_figure(
  filein = file.path(model_location, "plots", "recdevs2_withbars.png"),
  caption = "Estimated time series of recruitment deviations",
  alt_caption = "See the time-series table for tabular data.",
  label = "rec-devs"
)
sa4ss::add_figure(
  filein = file.path(model_location, "plots", "recruit_fit_bias_adjust.png"),
  caption = "Points are transformed variances. Red line shows current settings for bias adjustment specified in the control file. Blue line shows least squares estimate of alternative bias adjustment relationship for recruitment deviations (which may or may not be an improvement).",
  alt_caption = "The ramp fits the data for the end of the time series.",
  label = "bias-adjust"
)
sa4ss::add_figure(
  filein = file.path(model_location, "plots", "SR_curve.png"),
  caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in later years",
  alt_caption = "Many more points are above the estimated curve than below.",
  label = "bh-curve"
)
```

### Estimated Time Series

```{r figures-time-series, results = "asis"}
ignore <- fs::dir_ls(
  path = fs::path(model_location, "plots"),
  regex = "ts[14]_.+forecast|ts[79]_.+f.+_inter"
) |>
  tibble::as_tibble_col(column_name = "filein") |>
  dplyr::mutate(
    type = gsub("_", " ", gsub(".+ts[0-9]+_(.+)_[\\(i].+", "\\L\\1", perl = TRUE, filein)),
    type = ifelse(
      type == "relative spawning biomass",
      "fraction unfished",
      type
    ),
    caption = glue::glue("Estimated time series of {type}."),
    label = paste0("ts-", gsub("-\\(mt.+", "", gsub(pattern = " ", "-", type)))
  ) |>
  dplyr::select(filein, caption, label) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "See the time-series table for tabular data."
  )
```

### Fits to Data

```{r figures-index-fits, results = "asis"}
ignore <- fs::dir_ls(
  path = fs::path(model_location, "plots"),
  regex = "index2"
) |>
  tibble::as_tibble_col(column_name = "filein") |>
  dplyr::mutate(
    fleet_numeric = recode_fleet(gsub(".+_([A-Za-z \\.]+).png$", "\\1", filein)),
    fleet = recode_fleet_text(as.numeric(fleet_numeric)),
    caption = glue::glue("Fit to the {fleet}."),
    label = paste0("index2-cpuefit-", fleet_numeric)
  ) |>
  dplyr::arrange(fleet_numeric) |>
  dplyr::select(filein, caption, label) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "Fits are within the estimated confidence intervals."
  )
```

```{r figures-fit-lengths, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(model_location, "plots",  "comp_lenfit__aggregated_across_time.png"), 
  caption = "Length composition aggregated across years by fleet with the model estimated fit to the data by sex (green unsexed, red female, and blue male).",
  alt_caption = "The small fish in the WCGBTS are not fit well. Discard lengths are slightly underfit.",
  label = "comp-lenfit--aggregated-across-time"
)
ignore <- information_fit_figures |>
  dplyr::filter(type == "length") |>
  dplyr::select(filein, label, caption) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "Most large residuals are for smaller fish or early years."
  )
```

```{r figures-fit-age, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(model_location, "plots",  "comp_agefit__aggregated_across_time.png"), 
  caption = "Age composition aggregated across years by fleet with the model estimated fit to the data by sex (green unsexed, red female, and blue male).",
  alt_caption = "Some young fish are underfit but older fish were unbiased.",
  label = "comp-agefit--aggregated-across-time"
)
ignore <- information_fit_figures |>
  dplyr::filter(type %in% c("age", "conditional")) |>
  dplyr::arrange(
    factor(model[["fleet_type"]][fleet_number], levels = c(3, 1)),
    type
  ) |>
  dplyr::select(filein, label, caption) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "Most older fish younger than the plus group were fit well. Smaller fish generally had larger residuals."
  )
```

```{r figures-fit-mean-weight, results = "asis"}
ignote <- information_weight_figures  |>
  dplyr::select(filein, label, caption) |>
  purrr::pmap(
    .f = sa4ss::add_figure,
    alt_caption = "Fits were close to the mean but well within the confidence intervals."
  )
```

### Sensitivity and Retrospectives Analyses

```{r figures-sensitivity, results = "asis"}
# to do: figure out how to change spawning output versus spawning biomass
# for the type when appropriate but it does not matter here
ignore <- fs::dir_ls(
  fs::path(dirname(model_location), "sensitivities"),
  type = "file",
  regex = "compare2_|compare4|compare11|compare13.+flt7"
) |>
  tibble::as_tibble_col(column_name = "filein") |>
  dplyr::mutate(
    label = paste("sensitivity", gsub("^([0-9]+)-compare([0-9]+).+", "\\1-compare\\2", basename(filein)), sep = "-"),
    type = dplyr::case_when(
      grepl("compare[1-2]_", basename(filein)) ~ "Spawning biomass",
      grepl("compare[3-4]_", basename(filein)) ~ "Fraction unfished",
      grepl("compare11", basename(filein)) ~ "Annual recruitment deviations",
      grepl("compare13", basename(filein)) ~ "Recent survey index"
    ),
    caption = glue::glue(
      "{type} across a range of sensitivity analyses and the base model."
    )
  ) |>
    dplyr::select(filein, caption, label) |>
    purrr::pmap(
      .f = sa4ss::add_figure,
      alt_caption = "Most sensitives led to little change from the base model."
    )
```

```{r figures-retro, results = "asis"}
info <- read.csv(
  file = fs::dir_ls(
    dirname(model_location),
    regexp = "retrofigures4doc.csv",
    recurse = TRUE
  )
) |>
  dplyr::mutate(
    filein = gsub(
      paste0(".+", basename(here::here())),
      here::here(),
      filein
    ),
  ) |>
    purrr::pmap(
      .f = sa4ss::add_figure
    )
```

```{r figures-historical-make, cache = TRUE}
model_historical <- c(
  purrr::map(
    .x = head(fs::path(
      fs::dir_ls(
        fs::path(here::here(), "models"),
        type = "directory"
      ),
      "base",
      "base"
    ), -1),
    .f = r4ss::SS_output,
    verbose = FALSE,
    printstats = FALSE,
    covar = FALSE,
    compfile = NULL,
    NoCompOK = TRUE,
    wtfile = "",
    readwt = FALSE
  ),
  list(model)
)
names(model_historical) <- fs::dir_ls(
  fs::path(here::here(), "models"),
  type = "directory"
) |> basename()
r4ss::SSplotComparisons(
  r4ss::SSsummarize(c(model_historical), verbose = FALSE),
  plotdir = figures_location,
  subplots = c(2, 4),
  print = TRUE,
  plot = FALSE,
  legendlabels = names(model_historical),
  filenameprefix = "historical_"
)
```

```{r results = "asis"}
sa4ss::add_figure(
  fs::path(figures_location, "historical_compare2_spawnbio_uncertainty.png"),
  caption = glue::glue("Comparisons of spawning biomass (mt) between the current assessment and recent benchmark and update assessments since {min(names(model_historical))}."),
  alt_caption = "All trajectories of spawning biomass from the most recent assessments are encapsulated within the estimated uncertainty from the current model.",
  label = "historical-model-comparison-sb"
)
```
```{r results = "asis"}
sa4ss::add_figure(
  fs::path(figures_location, "historical_compare4_Bratio_uncertainty.png"),
  caption = glue::glue("Comparisons of fraction unfished between the current assessment and recent benchmark and update assessments since {min(names(model_historical))}."),
  alt_caption = "All trajectories of fraction unfished from the most recent assessments are encapsulated within the estimated uncertainty from the current model.",
  label = "historical-model-comparison-unfished"
)
```

### Likelihood Profiles

```{r figures-profiles, results = "asis"}
ignore <- tidyr::expand_grid(
  folder_list = fs::dir_ls(dirname(model_location), regexp = "base_profile"),
  string = c("compare1", "compare3", "piner")
) |>
  dplyr::mutate(
    filein = purrr::map2_chr(
      .x = folder_list,
      .y = string,
      .f = ~ fs::dir_ls(path = .x, regexp = .y)
    ),
    parameter = edit_string(
      sub("base_profile_", "", basename(names(folder_list)))
    ),
    label = paste("profile", gsub(" ", "-", parameter), string, sep = "-"),
    type = dplyr::case_when(
      grepl("piner", string) ~ "negative log-likelihood",
      grepl("compare[1-2]", string) ~ "spawning biomass",
      grepl("compare[3-4]", string) ~ "fraction unfished"
    ),
    caption = glue::glue(
      "Change in the {type} across a range of {parameter} values."
    )
  ) |>
    dplyr::select(filein, caption, label) |>
    purrr::pmap(
      .f = sa4ss::add_figure,
      alt_caption = "The base model represents the best fit to the data and the median or average of the profiled values."
    )
```

## Reference Points and Projections

```{r figures-reference-points, results = "asis"}
sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "SPR3_ratiointerval.png"
  ),
  caption = "Time series of fishing intensity which is $\\frac{1-SPR}{1-SPR_{45\\%}}$ where SPR is \\glsentrylong{spr}.",
  alt_caption = "Fishing intensity has been historically and recently below the target of 1.0.",
  label = "model-spr"
)

sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "SPR4_phase.png"
  ),
  caption = "Phase plot of biomass ratio vs. SPR ratio.
Each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year. Warmer colors (red) represent early years and colder colors (blue) represent recent years. Lines through the final point show 95 percent intervals based on the asymptotic uncertainty for each dimension.",
  alt_caption = "More years were over the fishing intensity target than under the biomass target but the majority of years have been within these bounds.",
  label = "model-phase"
)

sa4ss::add_figure(
  filein = fs::path(
    model_location,
    "plots",
    "yield2_yield_curve_with_refpoints.png"
  ),
  caption = "Yield curve with reference points.",
  alt_caption = "Current yield is lower than the maximum sustainable yield but the population is above biomass targets.",
  label = "model-yield"
)
```
